### ISSUE TITLE
minor: removing the import CACHE_DIR

### ISSUE THREAD

**Issue by ruiqi-zhong** [microsoft/automated-explanations#6]
https://github.com/microsoft/automated-explanations/blob/6f3a8388e72a231005d910151496c45b0fa12c14/sasc/modules/dictionary_module.py#LL17C1-L17C34

tried to run 

```python3 sasc/modules/dictionary_module.py ```

and the above line gives an error. 

```    
    from sasc.config import CACHE_DIR
ModuleNotFoundError: No module named 'sasc.config'
```

can simply delete since ```CACHE_DIR``` is not used anywhere in that script.

**Comment by csinva** [comment]
Thanks for the catch, just fixed!
